name: Release Docker Image

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Tag Name 
      run: |
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build -t ${{ github.repository }}:${{ github.ref_name }} .
    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push Docker Image to Docker Hub
      run: docker push ${{ github.repository }}:${{ github.ref_name }}
